import American from '../assets/img/image 65.png'
import Cherni from '../assets/img/cherni.png'
import Zeleni from '../assets/img/zeleni.png'
import Beli from '../assets/img/beli.png'

const fakePosters = [
  {
    id: 1,
    title: 'American Architecture',
    price: '3500',
    image: American,
    author: '@bomboclat',
    description: 'Когда я создавал этот постер, я думал о бесконечно вечном, и в итоге преисполнился в своем сознании. Больше постеров на моей странице!',
  },
  {
    id: 2,
    title: 'Black Disk',
    price: '4500',
    image: Cherni,
    author: '@bomboclat',
    description: 'Когда я создавал этот постер, я думал о бесконечно вечном, и в итоге преисполнился в своем сознании. Больше постеров на моей странице!',
  },
  {
    id: 3,
    title: 'Musik und Zukunft',
    price: '2999',
    image: Zeleni,
    author: '@bomboclat',
    description: 'Когда я создавал этот постер, я думал о бесконечно вечном, и в итоге преисполнился в своем сознании. Больше постеров на моей странице!',
  },
  {
    id: 4,
    title: 'Bootshard',
    price: '3500',
    image: Beli,
    author: '@bomboclat',
    description: 'Когда я создавал этот постер, я думал о бесконечно вечном, и в итоге преисполнился в своем сознании. Больше постеров на моей странице!',
  },
  {
    id: 5,
    title: 'American Architecture',
    price: '3500',
    author: '@bomboclat',
    author: '@bomboclat',
    image: American,
    description: 'Когда я создавал этот постер, я думал о бесконечно вечном, и в итоге преисполнился в своем сознании. Больше постеров на моей странице!',
  },
  {
    id: 6,
    title: 'Black Disk',
    price: '4500',
    author: '@bomboclat',
    image: Cherni,
    description: 'Когда я создавал этот постер, я думал о бесконечно вечном, и в итоге преисполнился в своем сознании. Больше постеров на моей странице!',
  },
  {
    id: 7,
    title: 'Musik und Zukunft',
    price: '2999',
    author: '@bomboclat',
    image: Zeleni,
    description: 'Когда я создавал этот постер, я думал о бесконечно вечном, и в итоге преисполнился в своем сознании. Больше постеров на моей странице!',
  },
  {
    id: 8,
    title: 'Bootshard',
    price: '3500',
    author: '@bomboclat',
    image: Beli,
    description: 'Когда я создавал этот постер, я думал о бесконечно вечном, и в итоге преисполнился в своем сознании. Больше постеров на моей странице!',
  },
  {
    id: 9,
    title: 'American Architecture',
    price: '3500',
    author: '@bomboclat',
    image: American,
    description: 'Когда я создавал этот постер, я думал о бесконечно вечном, и в итоге преисполнился в своем сознании. Больше постеров на моей странице!',
  },
  {
    id: 10,
    title: 'Black Disk',
    price: '4500',
    author: '@bomboclat',
    image: Cherni,
    description: 'Когда я создавал этот постер, я думал о бесконечно вечном, и в итоге преисполнился в своем сознании. Больше постеров на моей странице!',
  },
  {
    id: 11,
    title: 'Musik und Zukunft',
    price: '2999',
    author: '@bomboclat',
    image: Zeleni,
    description: 'Когда я создавал этот постер, я думал о бесконечно вечном, и в итоге преисполнился в своем сознании. Больше постеров на моей странице!',
  },
  {
    id: 12,
    title: 'Bootshard',
    price: '3500',
    author: '@bomboclat',
    image: Beli,
    description: 'Когда я создавал этот постер, я думал о бесконечно вечном, и в итоге преисполнился в своем сознании. Больше постеров на моей странице!',
  },
  {
    id: 13,
    title: 'American Architecture',
    price: '3500',
    author: '@bomboclat',
    image: American,
    description: 'Когда я создавал этот постер, я думал о бесконечно вечном, и в итоге преисполнился в своем сознании. Больше постеров на моей странице!',
  },
  {
    id: 14,
    title: 'Black Disk',
    price: '4500',
    author: '@bomboclat',
    image: Cherni,
    description: 'Когда я создавал этот постер, я думал о бесконечно вечном, и в итоге преисполнился в своем сознании. Больше постеров на моей странице!',
  },
  {
    id: 15,
    title: 'Musik und Zukunft',
    price: '2999',
    author: '@bomboclat',
    image: Zeleni,
    description: 'Когда я создавал этот постер, я думал о бесконечно вечном, и в итоге преисполнился в своем сознании. Больше постеров на моей странице!',
  },
  {
    id: 16,
    title: 'Bootshard',
    price: '3500',
    author: '@bomboclat',
    image: Beli,
    description: 'Когда я создавал этот постер, я думал о бесконечно вечном, и в итоге преисполнился в своем сознании. Больше постеров на моей странице!',
  },
];

export default fakePosters;
